# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Jone Zhang

# Description of the Site
description: 不要温和的走进那个良夜

# URL of Image of the Site
site-image: /assets/images/bg.jpg

# Keywords of the Site
# site-keywords: Site, Template, Theme

# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image 
heroimage: /assets/images/bg.jpg

# Social Media and Contact
email: zzztx_email@163.com
twitter_username: night_learner
github_username:  zzztx


# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Jone Zhang
# URL for the Image of the Author
author-image: /assets/images/zzz.png
# 60 Words About the Author
author-about: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget pharetra velit, dapibus bibendum ex. Maecenas vitae laoreet mauris, ac luctus metus. Aliquam luctus velit vel ipsum feugiat, vel venenatis mauris hendrerit. Sed at vulputate sapien, eget vehicula dolor. Aliquam volutpat pulvinar neque sit amet sodales.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
